name: TesteMongoDB
version: 0.0.1
description: A minimal web app for the developer that doesn’t want to be confused by too much going on.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  mongo_dart: any
  angular: ">=1.0.0 <2.0.0"
  web_components: ">=0.8.0 <0.9.0"
  browser: ">=0.10.0+2 <0.11.0"  
  http_server: any
transformers:
- angular
